# Generated by Django 2.2.7 on 2019-11-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormsPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=10, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('descricao', models.TextField()),
                ('outroTelefone', models.CharField(blank=True, max_length=29, null=True)),
                ('redesSociais', models.CharField(blank=True, max_length=99, null=True)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('statusConta', models.BooleanField(default=True)),
                ('atuacaoCidade', models.ManyToManyField(to='AppBase.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('wats', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_fotos')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBase.PrestadorServico')),
            ],
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='atuacaoEstado',
            field=models.ManyToManyField(to='AppBase.States'),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='formaPagamento',
            field=models.ManyToManyField(to='AppBase.FormsPayment'),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBase.User'),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='tipoServicos',
            field=models.ManyToManyField(to='AppBase.TypeService'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.IntegerField()),
                ('preco', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBase.User')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBase.PrestadorServico')),
            ],
        ),
    ]
