# Generated by Django 2.2.7 on 2019-12-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_novo',
            field=models.CharField(default='vit', max_length=30),
        ),
    ]
