# Generated by Django 2.2.7 on 2019-12-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0002_user_user_novo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_novo',
            field=models.CharField(max_length=30),
        ),
    ]
