# Generated by Django 2.2.7 on 2019-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0003_auto_20191130_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
